### ISSUE TITLE
React is not defined

### ISSUE THREAD

**Issue by DenJohX** [iMasterAle/react-datetimepicker-bootstrap#1]
Hi, great work!

I'd just installed the package via npm, but cannot use it because `DateTimePicker.js` is using an undefined `React` variable. 

Inspecting the code, there is a `var _react = require('react')` in line 11, but then its used with `React.createElement(...` in line 25. 

Also it might be useful if the package was shipped with the source code to use it in a module bundler.

**Comment by iMasterAle** [comment]
Hi @DenJohX !
Thanks! Did you install react? Because it is a peerDependencies.

Let me know

**Comment by DenJohX** [comment]
I was using it in an existing React project, the problem is React is not global and the built code is not importing it.

**Comment by iMasterAle** [comment]
Ok thanks, tonight I will try it and I will let know you.

**Comment by Randagio13** [comment]
Fix it! Thanks @DenJohX!
